version: "3"
services:
  web:
    image: weather-checking
    #image: dwoodbridge/weather-checking
    ports:
      - "80:80"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - API_KEY=${API_KEY}
    #network_mode: bridge
    container_name: web
    networks:
      - default
      - week1_network
  cron:
    image: cron
    #image: dwoodbridge/cron
    #network_mode: bridge
    container_name: cron
    depends_on:
      - web
    ports:
      - "80"
    networks:
      - default
      - week1_network
networks:
   week1_network:
    #external: false